server:
  port: 7000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookstoredb
    username: root
    password: Student@123
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update